### ISSUE TITLE
Afl live matches not loading. Replays working.

### ISSUE THREAD

**Issue by SaraGal** [aussieaddons/repo#75]
Debug log: 4306

**Comment by SaraGal** [comment]
Have tried following solutions from previous posts with the same issue with no luck.

**Comment by glennguy** [comment]
Hi @SaraGal, thanks for the debug log! 

This issue is common on cheap Android boxes it would seem unfortunately...

Your Android box is reporting that it is Widevine L1 certified. With many of these boxes however Google has revoked/banned the DRM keys contained on your device, or it has been made invalid due to custom firmware. I'm told that it's quite common to upgrade to custom firmware on these as the stock firmware is fairly garbage.

Another user has helpfully pointed out how it is worked around:

* Install Magisk (link [here](https://www.xda-developers.com/how-to-install-magisk/) - can't give you support with that one though sorry, you're on your own)
* Install the liboemcryptodisabler Magisk module to 'downgrade' your non-working L1 Widevine to L3 (SD only) level. You'll still get the full resolution available from the AFL service anyway.

Now the DRM process will work correctly and the stream won't fail.

**Comment by SaraGal** [comment]
Hi @glennguy. Thanks so much for your response. I will give that a go.
